apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-minimal-api-deployment
  labels:
    app: dotnet-api
spec:
  replicas: 2 # আপনার দুটি ওয়ার্কার নোড আছে, তাই ২ টি রেপ্লিকা দেওয়া হয়েছে
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
      - name: dotnet-api-container
        # এখানে আপনার ডকার হাবের ইমেজ নামটি দিন (যেমন: puremahadi/devops-dotnet-simple-project:latest)
        image: puremahadi/devops-dotnet-simple-project:V9-7a501db9f9ba2652a1f6a7d54c85a3492d0cb49c
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "256Mi" # ৫১২ থেকে কমিয়ে ২৫৬ করুন
            cpu: "200m"    # ৫০০ থেকে কমিয়ে ২০০ করুন
          requests:
            memory: "128Mi"
            cpu: "100m"