apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-minimal-api-deployment
  labels:
    app: dotnet-api
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
      - name: dotnet-api-container
        # কনফ্লিক্ট মার্কারগুলো সরিয়ে লেটেস্ট ইমেজ ট্যাগটি রাখুন
        image: puremahadi/devops-dotnet-simple-project:V15-6de70d13ea8f09753a7e6ddd367000f5342e1df7
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development" # এটি আপনাকে বিস্তারিত এরর দেখাবে
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
